import {
  Button,
  PlusCircle,
  Label,
  Input,
  Popover,
  PopoverContent,
  PopoverTrigger,
  ChevronsUpDown,
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  Check,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogClose,
  DialogTrigger,
  Textarea,
  Pin,
  Copy,
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
  buttonVariants,
} from "@/components/index";

import { useFetch } from "@/hooks/useFetch";
import { useToast } from "@/hooks/use-toast";
import { useFormat } from "@/hooks/useFormat";
import NoteCardItem from "./NoteCardItem";
import CodeMirror from "@uiw/react-codemirror";
import { githubDarkInit, githubLightInit } from "@uiw/codemirror-theme-github";

import { cn } from "@/lib/utils";

export const header = {
  Button,
  PlusCircle,
  Label,
  Input,
  Popover,
  PopoverContent,
  PopoverTrigger,
  ChevronsUpDown,
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  Check,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogClose,
  DialogTrigger,
  Textarea,
  cn,
  useToast,
  useFetch,
};

export const cardForm = {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
  DialogDescription,
  Button,
  Pin,
  Copy,
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
  useFetch,
  useToast,
  useFormat,
  NoteCardItem,
  buttonVariants,
};



export const cardItem = {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  githubDarkInit,
  githubLightInit,
  CodeMirror,
  useFormat,
};

export const cardContent = {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
};

export const basicSetup = {
  lineNumbers: false,
  highlightActiveLineGutter: false,
  highlightSpecialChars: false,
  history: false,
  foldGutter: false,
  drawSelection: false,
  dropCursor: false,
  allowMultipleSelections: false,
  indentOnInput: false,
  syntaxHighlighting: false,
  bracketMatching: false,
  closeBrackets: false,
  autocompletion: false,
  rectangularSelection: false,
  crosshairCursor: false,
  highlightActiveLine: false,
  highlightSelectionMatches: false,
  closeBracketsKeymap: false,
  searchKeymap: true,
  historyKeymap: false,
  foldKeymap: false,
  completionKeymap: false,
  lintKeymap: false,
};
